name: alias
description: Alias ids, generate const alias for group of random identifiers. No extra dependency.
version: 1.0.0
homepage: https://sudo.dog
repository: https://github.com/SudoDotDog/Dart-Alias.git

environment:
  sdk: ">=2.1.0 <3.0.0"

dev_dependencies:
  test: ^1.12.0
